version: '3.0'
services:
  server:
    build: server
    ports:
      - "8080:8080"
    command: bash -c "
      /scripts/wait-for-it.sh db:3306 --timeout=60 --strict &&
      go run main.go"
    env_file:
      - ./server/.env
    volumes:
      - type: bind
        source: ./server
        target: /server
    depends_on:
      - db
      - hardhat

  hardhat:
    build: blockchain
    ports:
      - "8545:8545"
    command: npm run node
    volumes:
      - type: bind
        source: ./blockchain
        target: /work

  db:
    image: mysql:8.0.29
    platform: linux/amd64 # For M1 mac...
    environment:
      MYSQL_DATABASE: 'knowtfolio-db'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
