name: setup-dotenv-cl
inputs:
  COGNITO_USER_POOL_ID:
    required: true
  COGNITO_CLIENT_ID:
    required: true
  COGNITO_IDENTITY_POOL_ID:
    required: true
  TINY_MCE_API_KEY:
    required: true
  
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        touch client/.env
        echo COGNITO_USER_POOL_ID=${{inputs.COGNITO_USER_POOL_ID}} >> client/.env
        echo COGNITO_CLIENT_ID=${{inputs.COGNITO_CLIENT_ID}} >> client/.env
        echo COGNITO_IDENTITY_POOL_ID=${{inputs.COGNITO_IDENTITY_POOL_ID}} >> client/.env
        echo ARTICLE_RESOURCES_S3_BUCKET=dev-knowtfolio-article-resources >> client/.env
        echo TINY_MCE_API_KEY=${{inputs.TINY_MCE_API_KEY}} >> client/.env
        echo CONTRACT_ADDRESS=0xd08db6d8Fb163182722e0D17fa8146f26a79BB6A >> client/.env
