openapi: 3.0.3
info:
    title: Knowtfolio Backend
    description: Blogging platform that leverages NFT to grow, buy and sell articles.
    version: "1.0"
servers:
    - url: http://localhost:8080
paths:
    /api/articles:
        post:
            tags:
                - articles
            summary: Create articles
            description: Create new article.
            operationId: articles#Create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                            content: <h1> Hello World! </h1>
                            signature: Praesentium repellendus est esse assumenda.
                            title: My Awesome Article
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                title: My Awesome Article
                "401":
                    description: 'unauthenticated: 認証に失敗した場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'article_not_found: 記事IDに対応する記事が見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/articles/{id}:
        delete:
            tags:
                - articles
            summary: Delete articles
            description: Delete article by id.
            operationId: articles#Delete
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteRequestBody'
                        example:
                            address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                            signature: Atque veritatis et in explicabo.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DeleteResponseBodyOnlyID'
                            example:
                                id: exampleId01
                "401":
                    description: 'unauthenticated: 認証に失敗した場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "403":
                    description: 'unauthorized: 操作を行う権限がない場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'article_not_found: 記事IDに対応する記事が見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - articles
            summary: Read articles
            description: Get article by id.
            operationId: articles#Read
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                title: My Awesome Article
                "404":
                    description: 'article_not_found: 記事IDに対応する記事が見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - articles
            summary: Update articles
            description: Update an article.
            operationId: articles#Update
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                            content: <h1> Hello World! </h1>
                            signature: Et voluptates quis nulla pariatur optio reiciendis.
                            title: My Awesome Article
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                content: <h1> Hello World! </h1>
                                id: exampleId01
                                title: My Awesome Article
                "401":
                    description: 'unauthenticated: 認証に失敗した場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "403":
                    description: 'unauthorized: 操作を行う権限がない場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'article_not_found: 記事IDに対応する記事が見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/articles/{id}/nft:
        post:
            tags:
                - articles
            summary: Tokenize articles
            description: MINT an NFT of the article.
            operationId: articles#Tokenize
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteRequestBody'
                        example:
                            address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                            signature: Tenetur animi.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ArticleTokenizeResult'
                            example:
                                cost: 5663578019026462848
                                hash: Asperiores repellendus.
                "401":
                    description: 'unauthenticated: 認証に失敗した場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "403":
                    description: 'unauthorized: 操作を行う権限がない場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'article_not_found: 記事IDに対応する記事が見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /articles/{id}:
        get:
            tags:
                - articles-html
            summary: Read HTML articles-html
            description: Get article's HTML by id.
            operationId: articles-html#Read HTML
            parameters:
                - name: id
                  in: path
                  description: 記事のID
                  required: true
                  schema:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                  example: exampleId01
            responses:
                "200":
                    description: IDに対応する記事のHTMLのバイナリ
                    content:
                        text/html; charset=UTF-8:
                            schema:
                                type: string
                                example: <h1> Hello World! </h1>
                                format: binary
                            example: <h1> Hello World! </h1>
                "404":
                    description: 'article_not_found: 記事IDに対応する記事が見つからなかった場合'
                    content:
                        application/vnd.goa.error+json:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        ArticleTokenizeResult:
            type: object
            properties:
                cost:
                    type: integer
                    description: トークン発行にかかったコスト
                    example: 5390535483770121101
                    format: int64
                hash:
                    type: string
                    description: トランザクションのハッシュ
                    example: Distinctio consectetur doloremque.
            example:
                cost: 2727825414143066766
                hash: Sapiente laboriosam veniam eos.
            required:
                - hash
                - cost
        CreateRequestBody:
            type: object
            properties:
                address:
                    type: string
                    description: ウォレットのアドレス
                    example: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                    pattern: ^0x[a-fA-F0-9]{40}$
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                signature:
                    type: string
                    description: '`address`のアカウントが行った署名'
                    example: Expedita consequatur repellat ut.
                title:
                    type: string
                    example: My Awesome Article
            description: 作成したい記事の情報
            example:
                address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                content: <h1> Hello World! </h1>
                signature: Consequatur aut asperiores quam illo cupiditate.
                title: My Awesome Article
            required:
                - title
                - content
                - address
                - signature
        CreateResponseBody:
            type: object
            properties:
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                id:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
                title:
                    type: string
                    example: My Awesome Article
            description: CreateResponseBody result type (default view)
            example:
                content: <h1> Hello World! </h1>
                id: exampleId01
                title: My Awesome Article
            required:
                - id
                - title
                - content
        DeleteRequestBody:
            type: object
            properties:
                address:
                    type: string
                    description: ウォレットのアドレス
                    example: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                    pattern: ^0x[a-fA-F0-9]{40}$
                signature:
                    type: string
                    description: '`address`のアカウントが行った署名'
                    example: Ipsa quis incidunt alias libero saepe.
            example:
                address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                signature: Provident nobis qui itaque ipsum vel.
            required:
                - address
                - signature
        DeleteResponseBodyOnlyID:
            type: object
            properties:
                id:
                    type: string
                    description: 記事のID
                    example: exampleId01
                    pattern: ^[A-Za-z0-9_-]+$
                    minLength: 11
                    maxLength: 11
            description: DeleteResponseBody result type (only-id view)
            example:
                id: exampleId01
            required:
                - id
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        UpdateRequestBody:
            type: object
            properties:
                address:
                    type: string
                    description: ウォレットのアドレス
                    example: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                    pattern: ^0x[a-fA-F0-9]{40}$
                content:
                    type: string
                    description: 本文のHTML
                    example: <h1> Hello World! </h1>
                signature:
                    type: string
                    description: '`address`のアカウントが行った署名'
                    example: Qui assumenda accusantium mollitia magni maxime voluptates.
                title:
                    type: string
                    example: My Awesome Article
            description: |-
                記事の更新内容
                リクエストに含まれるフィールドだけ更新される。
            example:
                address: '''0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'''
                content: <h1> Hello World! </h1>
                signature: Odit dolorem eius.
                title: My Awesome Article
            required:
                - address
                - signature
tags:
    - name: articles
      description: 記事サービス
    - name: articles-html
      description: SEO対策で、記事の表示だけ直接HTMLで返すためのサービス
