name: client

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: setup-dotenv
        uses: ./.github/actions/setup-dotenv
        with:
          ADMIN_WALLET_PRIVATE_KEY: ${{secrets.ADMIN_WALLET_PRIVATE_KEY}}
          AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY}}
          AWS_KNOWTFOLIO_ADMIN_SECRET_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_SECRET_KEY}}
          COGNITO_USER_POOL_ID: ${{secrets.COGNITO_USER_POOL_ID}}
          COGNITO_CLIENT_ID: ${{secrets.COGNITO_CLIENT_ID}}
          COGNITO_IDENTITY_POOL_ID: ${{secrets.COGNITO_IDENTITY_POOL_ID}}
          TINY_MCE_API_KEY: ${{secrets.TINY_MCE_API_KEY}}
      - name: check-format
        run: make checkfmt-cl
      - name: lint-test
        run: make lint-cl

  build:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: setup-dotenv
        uses: ./.github/actions/setup-dotenv
        with:
          ADMIN_WALLET_PRIVATE_KEY: ${{secrets.ADMIN_WALLET_PRIVATE_KEY}}
          AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY}}
          AWS_KNOWTFOLIO_ADMIN_SECRET_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_SECRET_KEY}}
          COGNITO_USER_POOL_ID: ${{secrets.COGNITO_USER_POOL_ID}}
          COGNITO_CLIENT_ID: ${{secrets.COGNITO_CLIENT_ID}}
          COGNITO_IDENTITY_POOL_ID: ${{secrets.COGNITO_IDENTITY_POOL_ID}}
          TINY_MCE_API_KEY: ${{secrets.TINY_MCE_API_KEY}}
      - name: build-client
        run: make client/dist
      - name: upload-client-dist
        uses: actions/upload-artifact@v3
        with:
          name: client-dist
          path: client/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: setup-dotenv
        uses: ./.github/actions/setup-dotenv
        with:
          ADMIN_WALLET_PRIVATE_KEY: ${{secrets.ADMIN_WALLET_PRIVATE_KEY}}
          AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY}}
          AWS_KNOWTFOLIO_ADMIN_SECRET_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_SECRET_KEY}}
          COGNITO_USER_POOL_ID: ${{secrets.COGNITO_USER_POOL_ID}}
          COGNITO_CLIENT_ID: ${{secrets.COGNITO_CLIENT_ID}}
          COGNITO_IDENTITY_POOL_ID: ${{secrets.COGNITO_IDENTITY_POOL_ID}}
          TINY_MCE_API_KEY: ${{secrets.TINY_MCE_API_KEY}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TERRAFORM_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_TERRAFORM_USER_SECRET_KEY }}
          aws-region: ap-northeast-1
      - name: download-server-bin
        uses: actions/download-artifact@v3
        with:
          name: client-dist
          path: client/dist
      - name: load-dotenv
        uses: xom9ikk/dotenv@v2
        with:
          path: client
      - name: upload-client
        working-directory: client
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_TERRAFORM_USER_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_TERRAFORM_USER_SECRET_KEY}}
          AWS_DEFAULT_REGION: ap-northeast-1
        run: |
          aws s3 sync ./dist s3://$CLIENT_S3_BUCKET --exact-timestamps
          aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_DISTRIBUTION_ID --paths "/*"
