name: Infrastructure Test

on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: setup-dotenv-sv
        uses: ./.github/actions/setup-dotenv-sv
        with:
          ADMIN_WALLET_PRIVATE_KEY: ${{secrets.ADMIN_WALLET_PRIVATE_KEY}}
          AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY}}
          AWS_KNOWTFOLIO_ADMIN_SECRET_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_SECRET_KEY}}
      - name: setup-credentials
        run: |
          touch infrastructure/.aws/config
          echo [profile knowtfolio] >> infrastructure/.aws/config
          echo region = ap-northeast-1 >> infrastructure/.aws/config
          echo output = json >> infrastructure/.aws/config
          touch infrastructure/.aws/credentials
          echo [knowtfolio] >> infrastructure/.aws/credentials
          echo aws_access_key_id = ${{secrets.AWS_TERRAFORM_USER_ACCESS_KEY}} >> infrastructure/.aws/credentials
          echo aws_secret_access_key = ${{secrets.AWS_TERRAFORM_USER_SECRET_KEY}} >> infrastructure/.aws/credentials
      - name: init-terraform
        run: make init-tf
      - name: check-terraform-format
        run: make checkfmt-tf
      - name: terraform-test
        run: make plan-tf
