name: Server deploy

on:
  push:
    branches:
      - reibomaru/code-deploy

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: setup-dotenv
        uses: ./.github/actions/setup-dotenv
        with:
          ADMIN_WALLET_PRIVATE_KEY: ${{secrets.ADMIN_WALLET_PRIVATE_KEY}}
          AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY}}
          AWS_KNOWTFOLIO_ADMIN_SECRET_KEY: ${{secrets.AWS_KNOWTFOLIO_ADMIN_SECRET_KEY}}
      - name: check-format
        run: make checkfmt-sv
      - name: go-test
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: setup-dotenv
        run: |
          touch server/.env
          echo DB_URI="admin:password@tcp(knowtfolio-db.c9irp7zzw9uy.ap-northeast-1.rds.amazonaws.com)/knowtfolio_db" >> server/.env
          echo ADMIN_PRIVATE_KEY=${{secrets.ADMIN_WALLET_PRIVATE_KEY}} >> server/.env
          echo CONTRACT_ADDRESS=0xd08db6d8Fb163182722e0D17fa8146f26a79BB6A >> server/.env
          echo NETWORK_URI=https://polygon-mumbai.g.alchemy.com/v2/ZRG81-lcDf9T69OmxipvuoO-FMMFAOoH >> server/.env
          echo CHAIN_ID=80001 >> server/.env
          echo AWS_ACCESS_KEY=${{secrets.AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY}} >> server/.env
          echo AWS_SECRET_KEY=${{secrets.AWS_KNOWTFOLIO_ADMIN_SECRET_KEY}} >> server/.env
          echo AWS_REGION=ap-northeast-1 >> server/.env
          echo S3_BUCKET_NAME=dev-knowtfolio-nfts >> server/.env
      - name: build-server
        run: make build-sv
      - name: upload-server-bin
        uses: actions/upload-artifact@v3
        with:
          name: server-binary
          path: server/server
      - name: upload-env
        uses: actions/upload-artifact@v3
        with:
          name: env
          path: server/.env
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TERRAFORM_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_TERRAFORM_USER_SECRET_KEY }}
          aws-region: ap-northeast-1
      - name: download-env
        uses: actions/download-artifact@v3
        with: 
          name: env
          path: infrastructure/deploy/server
      - name: download-server-bin
        uses: actions/download-artifact@v3
        with: 
          name: server-binary
          path: infrastructure/deploy/server
      - name: upload-to-s3
        run: |
          zip -r artifacts.zip .
          aws s3 cp ./artifacts.zip s3://dev-knowtfolio-code-deploy/artifacts/${{ github.sha }}.zip
        working-directory: infrastructure/deploy/server
      - name: create-aws-deploy
        run: >
          aws deploy create-deployment
          --application-name knowtfolio
          --deployment-group-name backend
          --s3-location bucket=dev-knowtfolio-code-deploy,key=artifacts/${{ github.sha }}.zip,bundleType=zip