on: [push, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: server-test
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v2
      - name: create-dotenv
        run: |
          touch server/.env
          echo DB_URI="root:password@tcp(db:3306)/knowtfolio-db" >> server/.env
          echo ADMIN_PRIVATE_KEY=${{secrets.ADMIN_WALLET_PRIVATE_KEY}} >> server/.env
          echo CONTRACT_ADDRESS=0xd08db6d8Fb163182722e0D17fa8146f26a79BB6A >> server/.env
          echo NETWORK_URI=https://polygon-mumbai.g.alchemy.com/v2/ZRG81-lcDf9T69OmxipvuoO-FMMFAOoH >> server/.env
          echo CHAIN_ID=80001 >> server/.env
          echo AWS_ACCESS_KEY=${{secrets.AWS_KNOWTFOLIO_ADMIN_ACCESS_KEY}} >> server/.env
          echo AWS_SECRET_KEY=${{secrets.AWS_KNOWTFOLIO_ADMIN_SECRET_KEY}} >> server/.env
          echo AWS_REGION=ap-northeast-1 >> server/.env
          echo S3_BUCKET_NAME=dev-knowtfolio-nfts >> server/.env
      - name: check-format
        run: make checkfmt-sv
      - name: go-test
        run: make test
